version: '2'
services:
    jenkintest3-app:
        image: jenkintest3
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jenkintest3-mysql:3306/jenkintest3?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jenkintest3-mysql:
        extends:
            file: mysql.yml
            service: jenkintest3-mysql
